source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
pod 'Google-Mobile-Ads-SDK', '~> 6.12.2'
pod 'GoogleAnalytics-iOS-SDK', '~> 3.0.9'
pod 'MBProgressHUD', '~> 0.8'
pod 'FlurrySDK', '~> 5.4'
